In [2]:
import pandas as pd

In [3]:
path = r"H:\python\trabalho_3etapa\atividade_4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [4]:
# pip install openpyxl
# Lê a tabela pulando o topo 
dados = pd.read_excel(path, engine="openpyxl", header=2)
dados.head()

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [5]:
# 5 - Crie uma tabela de população agregada por estado

dados_estado = dados.groupby("UF")[["População 2010 (Alterações de Limites até 2022)1", "População Censo 2022"]].sum().reset_index()
dados_estado.head()

   UF  População 2010 (Alterações de Limites até 2022)1  População Censo 2022
0  AC                                          733559.0              830018.0
1  AL                                         3120887.0             3127683.0
2  AM                                         3483985.0             3941613.0
3  AP                                          669526.0              733759.0
4  BA                                        14017071.0            14141626.0

In [6]:
# 6 - Organize essa tabela por população que mais cresceu entre 2022 e 2010 (Faça a diferença se necessário)

dados_estado["Crescimento"] = dados_estado["População Censo 2022"] - dados_estado["População 2010 (Alterações de Limites até 2022)1"]

# maior para o menor
dados_estado_ordenado = dados_estado.sort_values(by="Crescimento", ascending=False)
dados_estado_ordenado.head()

,UF,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento
27,SP,41262199.0,44411238.0,3149039.0
25,SC,6248436.0,7610361.0,1361925.0
9,GO,6001789.0,7056495.0,1054706.0
19,PR,10444526.0,11444380.0,999854.0
11,MG,19597330.0,20539989.0,942659.0

In [7]:
# 7 - Salve essa tabela nova em csv na pasta do seu projeto
dados_estado_ordenado.to_csv("populacao_por_estado.csv", sep=";", index=False)

In [8]:
# 8 - Agora trabalhe por município

dados_municipio = dados.groupby(["UF", "NOME DO MUNICÍPIO"])[["População 2010 (Alterações de Limites até 2022)1", "População Censo 2022"]].sum().reset_index()
dados_municipio.head()

,UF,NOME DO MUNICÍPIO,População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,AC,Acrelândia,12538.0,14021.0
1,AC,Assis Brasil,6072.0,8100.0
2,AC,Brasiléia,21398.0,26000.0
3,AC,Bujari,8471.0,12917.0
4,AC,Capixaba,8798.0,10392.0

In [9]:
# 9 - Organize essa tabela por população que mais cresceu entre 2022 e 2010 (Faça a diferença se necessário)

dados_municipio["Crescimento"] = dados_municipio["População Censo 2022"] - dados_municipio["População 2010 (Alterações de Limites até 2022)1"]
dados_municipio_ordenado = dados_municipio.sort_values(by="Crescimento", ascending=False)
dados_municipio.head()

,UF,NOME DO MUNICÍPIO,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,Crescimento
0,AC,Acrelândia,12538.0,14021.0,1483.0
1,AC,Assis Brasil,6072.0,8100.0,2028.0
2,AC,Brasiléia,21398.0,26000.0,4602.0
3,AC,Bujari,8471.0,12917.0,4446.0
4,AC,Capixaba,8798.0,10392.0,1594.0

In [10]:
# 10 - Salve essa tabela nova em csv na pasta do seu projeto

dados_municipio_ordenado.to_csv("populacao_por_municipio.csv", sep=";", index=False)